USE [master]
GO

/****** Object:  Database [WebDota]    Script Date: 12/21/2016 12:29:38 PM ******/
DROP DATABASE [WebDota]
GO

/****** Object:  Database [WebDota]    Script Date: 12/21/2016 12:29:38 PM ******/
CREATE DATABASE [WebDota]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebDota', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WebDota.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebDota_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WebDota_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [WebDota] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebDota].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebDota] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebDota] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebDota] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebDota] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebDota] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebDota] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebDota] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebDota] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebDota] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebDota] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebDota] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebDota] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebDota] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebDota] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebDota] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebDota] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebDota] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebDota] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebDota] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebDota] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebDota] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebDota] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebDota] SET RECOVERY FULL 
GO

ALTER DATABASE [WebDota] SET  MULTI_USER 
GO

ALTER DATABASE [WebDota] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebDota] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebDota] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebDota] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebDota] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebDota] SET  READ_WRITE 
GO


